#!/bin/bash 

if [ ! -f install ]; then
echo 'install mush be run within its container folder' 1>&2
exit 1
fi

CURDIR='pwd'
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

gofmt -w src

go install Music

export GOPATH="$OLDGOPATH"
echo 'finished'
